FROM node:20.17-alpine AS base

WORKDIR /app
COPY package*.json ./

FROM base AS production
RUN npm i --production

FROM base AS dependencies
RUN npm i --production=false

FROM dependencies AS build
COPY . .
RUN npm run build

FROM production AS release
COPY --from=build /app/dist ./dist
COPY --from=production /app/node_modules ./node_modules

CMD ["node", "dist/main.js"]
