services:
  wordpress:
    image: wordpress:php8.2-apache
    restart: always
    ports:
      - 8080:80
    env_file: .env.wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db      
  db:
    image: mysql:8.0
    restart: always
    env_file: .env.mysql
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
